# Generated by Django 3.2.4 on 2021-07-01 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_book_published_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='long_describtion',
            new_name='long_description',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='short_describtion',
            new_name='short_description',
        ),
    ]
